source 'https://rubygems.org'
#ruby '2.0.0'

gem 'rails', '4.0.2'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'figaro'
gem 'haml-rails'
gem 'high_voltage'
gem 'simple_form'
gem 'therubyracer'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
end

gem 'will_paginate-bootstrap'

gem 'rethinkdb'
gem 'puma', '2.2.0'
